name: RSRG
favicon: null
layout_spectrum: 0.50483
typography_spectrum: 0.95463
title: Random Stuff Random Guy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76348078-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.09240091568790376
  lightness: 0.9799264487810433
  saturation: 0.9728047067765146
  rhythmicContrast: 0.7378142469096929
purpose: []
